title: ARC
theme: minima
author: harijith1
email: harijith1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to arc! Arc is the way of the future.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage


